/* Green Acres Bowl — service worker (generated by src/build.mjs) */
const VERSION = '202609071519';
const SHELL = `gab-shell-${VERSION}`;
const RUNTIME = `gab-runtime-${VERSION}`;
const OFFLINE_URL = 'offline.html';
const PRECACHE = [
  "./",
  "index.html",
  "about.html",
  "employment-opportunities.html",
  "reviews.html",
  "snack-bar-menu.html",
  "11th-frame-club.html",
  "leagues.html",
  "pro-shop.html",
  "specials-and-events.html",
  "reservations.html",
  "rates.html",
  "gallery.html",
  "contact-us.html",
  "offline.html",
  "manifest.webmanifest",
  "favicon.ico",
  "assets/css/site.css",
  "assets/js/site.js",
  "assets/fonts/InterVariable.woff2",
  "assets/brand/gab-logo.png",
  "assets/icons/apple-touch-icon.png",
  "assets/icons/favicon-32.png",
  "assets/icons/icon-192.png",
  "assets/icons/icon-512.png",
  "assets/icons/icon-96.png",
  "assets/icons/icon-maskable-512.png"
];

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(SHELL);
    // Add individually so one missing optional asset never blocks install.
    await Promise.allSettled(PRECACHE.map((u) => cache.add(new Request(u, { cache: 'reload' }))));
  })());
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k.startsWith('gab-') && k !== SHELL && k !== RUNTIME).map((k) => caches.delete(k)));
    if (self.registration.navigationPreload) { try { await self.registration.navigationPreload.enable(); } catch (e) {} }
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') self.skipWaiting();
});

const isSameOrigin = (url) => url.origin === self.location.origin;
const stripSearch = (req) => { const u = new URL(req.url); u.search = ''; return u.href; };

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (!isSameOrigin(url)) return; // maps, fonts CDN etc. go straight to the network

  // Pages: network first (fresh content), fall back to cache, then the offline page.
  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      try {
        const preload = await event.preloadResponse;
        if (preload) { const c = await caches.open(SHELL); c.put(stripSearch(request), preload.clone()); return preload; }
        const fresh = await fetch(request);
        const c = await caches.open(SHELL); c.put(stripSearch(request), fresh.clone());
        return fresh;
      } catch (e) {
        const cached = await caches.match(stripSearch(request)) || await caches.match(request);
        return cached || caches.match(OFFLINE_URL);
      }
    })());
    return;
  }

  // Static assets: cache first, refresh in the background (stale-while-revalidate).
  event.respondWith((async () => {
    const cached = await caches.match(request);
    const network = fetch(request).then(async (res) => {
      if (res && res.ok && (res.type === 'basic')) { const c = await caches.open(RUNTIME); c.put(request, res.clone()); }
      return res;
    }).catch(() => null);
    return cached || (await network) || new Response('', { status: 504, statusText: 'Offline' });
  })());
});
